"""Report delivery.

A ``Deliverer`` takes a rendered PDF and puts it somewhere. ``LocalDeliverer`` (the default)
just reports the path. ``DriveDeliverer`` and ``EmailDeliverer`` are the production paths — they
are unit-tested with fakes but stay off unless ``DELIVER_CHANNEL`` is set, and the Drive one
needs the optional ``delivery`` extra installed.
"""

from __future__ import annotations

import os
import smtplib
from collections.abc import Callable
from dataclasses import dataclass
from email.message import EmailMessage
from pathlib import Path
from typing import Protocol

from meta_reporting.config import Config, DeliveryChannel


@dataclass(frozen=True, slots=True)
class DeliveryResult:
    channel: str
    destination: str
    ok: bool
    detail: str = ""


class Deliverer(Protocol):
    def deliver(self, pdf_path: Path, *, subject: str) -> DeliveryResult: ...


class LocalDeliverer:
    def deliver(self, pdf_path: Path, *, subject: str) -> DeliveryResult:
        return DeliveryResult("local", str(pdf_path.resolve()), ok=pdf_path.exists())


class EmailDeliverer:
    """SMTP delivery. Reads EMAIL_SMTP_HOST/PORT/USERNAME/PASSWORD/TO from the environment."""

    def __init__(
        self,
        *,
        host: str,
        port: int,
        username: str,
        password: str,
        recipients: list[str],
        smtp_factory: type[smtplib.SMTP] = smtplib.SMTP,
    ) -> None:
        self.host = host
        self.port = port
        self.username = username
        self.password = password
        self.recipients = recipients
        self._smtp_factory = smtp_factory

    @classmethod
    def from_env(cls) -> EmailDeliverer:
        return cls(
            host=_require_env("EMAIL_SMTP_HOST"),
            port=int(os.environ.get("EMAIL_SMTP_PORT", "587")),
            username=_require_env("EMAIL_USERNAME"),
            password=_require_env("EMAIL_PASSWORD"),
            recipients=[r.strip() for r in _require_env("EMAIL_TO").split(",")],
        )

    def deliver(self, pdf_path: Path, *, subject: str) -> DeliveryResult:
        message = EmailMessage()
        message["From"] = self.username
        message["To"] = ", ".join(self.recipients)
        message["Subject"] = subject
        message.set_content("Report attached. Generated by the Halo Skin reporting pipeline.")
        message.add_attachment(
            pdf_path.read_bytes(),
            maintype="application",
            subtype="pdf",
            filename=pdf_path.name,
        )
        with self._smtp_factory(self.host, self.port) as smtp:
            smtp.starttls()
            smtp.login(self.username, self.password)
            smtp.send_message(message)
        return DeliveryResult("email", ", ".join(self.recipients), ok=True)


class DriveDeliverer:
    """Google Drive upload. Needs the ``delivery`` extra and a service-account JSON."""

    def __init__(
        self,
        *,
        folder_id: str,
        service: object | None = None,
        media_factory: Callable[[str, str], object] | None = None,
    ) -> None:
        self.folder_id = folder_id
        self._service = service
        self._media_factory = media_factory or _default_media_factory

    @classmethod
    def from_env(cls) -> DriveDeliverer:
        return cls(folder_id=_require_env("DRIVE_FOLDER_ID"))

    def _build_service(self) -> object:
        if self._service is not None:
            return self._service
        try:
            from google.oauth2 import service_account
            from googleapiclient.discovery import build
        except ModuleNotFoundError as exc:  # pragma: no cover - exercised via message only
            raise RuntimeError(
                "Drive delivery needs the optional extra: `uv sync --extra delivery`"
            ) from exc
        creds = service_account.Credentials.from_service_account_file(
            _require_env("GOOGLE_APPLICATION_CREDENTIALS"),
            scopes=["https://www.googleapis.com/auth/drive.file"],
        )
        self._service = build("drive", "v3", credentials=creds)
        return self._service

    def deliver(self, pdf_path: Path, *, subject: str) -> DeliveryResult:
        service = self._build_service()
        media = self._media_factory(str(pdf_path), "application/pdf")
        created = (
            service.files()  # type: ignore[attr-defined]
            .create(
                body={"name": pdf_path.name, "parents": [self.folder_id]},
                media_body=media,
                fields="id,webViewLink",
            )
            .execute()
        )
        return DeliveryResult("drive", created.get("webViewLink", created["id"]), ok=True)


def get_deliverer(config: Config) -> Deliverer:
    match config.delivery:
        case None | DeliveryChannel.LOCAL:
            return LocalDeliverer()
        case DeliveryChannel.EMAIL:
            return EmailDeliverer.from_env()
        case DeliveryChannel.DRIVE:
            return DriveDeliverer.from_env()


def _default_media_factory(path: str, mimetype: str) -> object:
    from googleapiclient.http import MediaFileUpload

    return MediaFileUpload(path, mimetype=mimetype)


def _require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"{name} is required for this delivery channel")
    return value
